In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/dataset_study (2).csv")

In [4]:
print(df.shape)

(5000, 3)

In [5]:
df.head(5)

   student_id   "study hours"   "scores"
0           1            9.15      91.91
1           2            9.37      86.81
2           3            2.86      53.39
3           4            8.30      85.52
4           5            6.42      77.98

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      5000 non-null   int64
 1    "study hours"  5000 non-null   float64
 2    "scores"       5000 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

In [7]:
df.describe()

        student_id   "study hours"     "scores"
count  5000.000000     5000.000000  5000.000000
mean   2500.500000        5.031654    64.969712
std    1443.520003        2.910579    17.657329
min       1.000000        0.000000    15.520000
25%    1250.750000        2.520000    51.717500
50%    2500.500000        5.050000    64.975000
75%    3750.250000        7.582500    78.710000
max    5000.000000       10.000000   100.000000

In [8]:
df.isnull().sum()

student_id        0
 "study hours"    0
 "scores"         0
dtype: int64

In [9]:
df.columns = df.columns.str.strip().str.replace('"', '')

x = df['study hours'].values
y = df['scores'].values

In [11]:
w = 0
b = 0
lr = 0.01

In [12]:
np.random.seed(42)
idx = np.random.permutation(len(x))
split = int(0.8 * len(x))
train_idx, test_idx = idx[:split], idx[split:]

x_train, x_test = x[train_idx], x[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

In [27]:
w = 0
b = 0
lr = 0.01

In [30]:
for step in range(1000):
    y_pred = w * x_train + b

    loss = np.mean((y_pred - y_train) ** 2)

    dw = np.mean(2 * (y_pred - y_train) * x_train)
    db = np.mean(2 * (y_pred - y_train))

    w = w - lr * dw
    b = b - lr * db

    if step % 100 == 0:
        print(f"Step {step}, b: {b:.4f} Loss: {loss:.4f}")

print(f"Final w: {w:.4f}, Final b: {b:.4f}")

Step 0, b: 39.5091 Loss: 99.7919
Step 100, b: 39.5100 Loss: 99.7919
Step 200, b: 39.5105 Loss: 99.7919
Step 300, b: 39.5108 Loss: 99.7919
Step 400, b: 39.5110 Loss: 99.7919
Step 500, b: 39.5111 Loss: 99.7919
Step 600, b: 39.5112 Loss: 99.7919
Step 700, b: 39.5113 Loss: 99.7919
Step 800, b: 39.5113 Loss: 99.7919
Step 900, b: 39.5113 Loss: 99.7919
Final w: 5.0572, Final b: 39.5113

In [31]:
y_test_pred = w * x_test + b

test_mse = np.mean((y_test_pred - y_test) ** 2)
print(f"Test MSE: {test_mse:.4f}")

for i in range(10):
    print(f"Predicted: {y_test_pred[i]:.2f}, Actual: {y_test[i]:.2f}")

Test MSE: 95.3535
Predicted: 44.52, Actual: 44.78
Predicted: 47.30, Actual: 50.43
Predicted: 89.48, Actual: 80.76
Predicted: 53.87, Actual: 34.55
Predicted: 45.88, Actual: 52.82
Predicted: 84.87, Actual: 82.59
Predicted: 46.04, Actual: 53.36
Predicted: 79.77, Actual: 80.00
Predicted: 53.92, Actual: 33.82
Predicted: 40.22, Actual: 38.97